apiVersion: v1
kind: Service
metadata:
  name: {{ include "atuin.fullname" . }}
  labels:
    {{- include "atuin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:

    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http


    {{- if .Values.atuin.metrics.enabled }}
    - port: {{ .Values.atuin.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}

  selector:
    {{- include "atuin.selectorLabels" . | nindent 4 }}
