{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "atuin.fullname" . }}
spec:
  endpoints:
  - interval: 60s
    path: /metrics
    port: metrics
  selector:
    matchLabels:
      {{- include "atuin.selectorLabels" . | nindent 6 }}
{{- end}}
